// AussieTowns/ClientApp/app/components/shared/schedule.component.ts
﻿import { Component, Input } from '@angular/core';
import { IMyOptions, IMyDateModel } from 'mydatepicker';
import { FormBuilder, FormGroup } from '@angular/forms';

@Component({
    selector: 'schedule',
    template: require('./schedule.component.html')
})

export class ScheduleComponent {
    @Input('scheduleIntance') model: FormGroup;

    public repeatPeriods = [
        { value: '1', display: 'Daily' },
        { value: '2', display: 'Weekly' },
        { value: '3', display: 'Monthly' }
    ];

    private startDatePickerOptions: IMyOptions = {
        dateFormat: 'dd/mm/yyyy',
        height: '34px',
        width: '250px',
        showTodayBtn: true,
        showClearDateBtn: false,
        markCurrentDay: true
    };

    private endDatePickerOptions: IMyOptions = {
        dateFormat: 'dd/mm/yyyy',
        height: '34px',
        width: '250px',
        showTodayBtn: true,
        showClearDateBtn: false,
        markCurrentDay: true
    };

    constructor(private fb: FormBuilder) { }

    onStartDateChanged(event: IMyDateModel) {
        let d: Date = event.jsdate;

        // set previous of selected date
        d.setDate(d.getDate() - 1);

        // Get new copy of options in order the date picker detect change
        let copy: IMyOptions = JSON.parse(JSON.stringify(this.endDatePickerOptions));
        copy.disableUntil = {
            year: d.getFullYear(),
            month: d.getMonth() + 1,
            day: d.getDate()
        };
        this.endDatePickerOptions = copy;
    }

    onEndDateChanged(event: IMyDateModel) {
    }

    onStartTimeInput(event) {
        
    }
}
﻿<form [formGroup]="model">
    <div class="schedule-wrapper">
        <div class="left25">
            Date
        </div>
        <div class="left25">
            Start time
        </div>
        <div class="left25">
            Duration
        </div>
        <div class="left25">
            <input type="checkbox" formControlName="isRepeated" (change)="isRepeated = !isRepeated" style="width: 20px;"> Repeat
        </div>
        <div class="clear"></div>
        <div class="left25">
            <my-date-picker [options]="startDatePickerOptions" (dateChanged)="onStartDateChanged($event)" formControlName="startDate"></my-date-picker>
        </div>
        <div class="left25">
            <input class="form-control" type="text" placeholder="hh:mm" (keyup)="onStartTimeInput($event)" formControlName="startTime">
        </div>
        <div class="left25">
            <timepicker formControlName="duration"></timepicker>
        </div>
        <div class="left25" [hidden]="!isRepeated">
            <div *ngFor="let period of repeatPeriods">
                <p>
                    <input type="radio" formControlName="repeatPeriod"
                           [value]="period.value">
                    {{period.display}}
                </p>
            </div>
            <div>
                <p style="width: 30px; display: inline-block; bottom: 10px; position: relative;">Until</p>
                <my-date-picker [options]="endDatePickerOptions" (dateChanged)="onEndDateChanged($event)" formControlName="endDate"></my-date-picker>                
            </div>
        </div>
    </div>
    <div class="clear"></div>
</form>

// AussieTown.VueClient/src/components/shared/schedule.component.vue
﻿<template>
        <div class="schedule-wrapper">
            <div class="left25">
                Date
            </div>
            <div class="left25">
                Start time
            </div>
            <div class="left25">
                Duration
            </div>
            <div class="left25">
                <input type="checkbox" v-model="isRepeated"   
                    v-bind:true-value="true"
                    v-bind:false-value="false" style="width: 20px;"> Repeat
            </div>
            <div class="left25">
                <datepicker v-model="startDate"></datepicker>
            </div>
            <div class="left25">
                <vue-timepicker v-model="startTime"></vue-timepicker>
                <!--<input class="form-control" type="text" placeholder="hh:mm" (keyup)="onStartTimeInput($event)" formControlName="startTime">-->
            </div>
            <div class="left25">
                <vue-timepicker v-model="duration"></vue-timepicker>
                <!--<timepicker formControlName="duration"></timepicker>-->
            </div>
            <div class="left25" v-show="isRepeated">
                <div v-for="period of repeatPeriods">
                    <label class="radio">
                        <input type="radio" name="period" :value="period.value" v-model="selectedPeriod">
                        {{period.display}}
                    </label>
                </div>
                <div>
                    <p style="width: 30px; display: inline-block; bottom: 10px; position: relative;">Until</p>
                    <datepicker v-model="endDate"></datepicker>
                </div>
            </div>
        </div>
</template>

<script lang="ts">
import ScheduleComponent from "./schedule.component.ts";
export default ScheduleComponent;
</script>
