// FunWithLocal.WebApi/ClientApp/app/components/shared/miniprofile.component.ts
﻿import { Component, Input, Output, EventEmitter } from '@angular/core';
import { User } from '../../model/user';

@Component({
    selector: 'miniprofile',
    template: require('./miniprofile.component.html'),
    styles: [require('./miniprofile.component.css')]
})
export class MiniProfileComponent {
    @Input() data: any;
    @Input() isRemovable: boolean = true;
    @Output() removeUser = new EventEmitter();

    userId: number;
    profileUrl: string;
    profileImageUrl: string;
    fullName: string;
    shortDescription: string;

    ngOnInit(): void {
        this.userId = this.data.id;
        this.profileImageUrl = this.data.photoUrl;
        this.fullName = this.data.fullname;
        this.shortDescription = this.data.shortDescription;
    }

    onRemoveUser() {
        this.removeUser.emit(this.data);
    }
}

// AussieTown.VueClient/src/component/shared/miniprofile.component.ts
﻿import Vue from "vue";
import { Component, Inject, Watch, Prop } from "vue-property-decorator";
import axios from "axios";

@Component({
    name: "MiniProfile"
})

export default class MiniProfileComponent extends Vue{
    @Prop data: any;
    @Prop isRemovable: boolean;

    userId: number;
    profileUrl: string;
    profileImageUrl: string;
    fullName: string;
    shortDescription: string;

    created() {
        this.userId = this.data.id;
        this.profileImageUrl = this.data.photoUrl;
        this.profileUrl = '';
        this.fullName = this.data.fullname;
        this.shortDescription = this.data.shortDescription;        
    }

    onRemoveUser() {
        this.$emit("removeUser", this.data);
    }
}
