// AussieTown.VueClient/src/component/shared/miniprofile.component.vue
﻿<template>
    <div :id="userId" class="miniprofile-wrapper">
        <div class="overlay" @click="onRemoveUser()" v-if="!isRemovable">
            <span class="glyphicon glyphicon-remove-sign"></span>
        </div>
        <div class="photo_wrapper">
            <a :href="profileUrl" target="_blank">
                <img class="profile_photo_img" :src="profileImageUrl" width="50" height="50" :alt="fullName">
            </a>
        </div>
        <div class="text_wrapper">
            <div>
                <a class="user" :href="profileUrl" target="_blank">{{fullName}}</a>
            </div>
            <div>
                <span>{{shortDescription}}</span>
            </div>
        </div>
    </div>
</template>

<script lang="ts">
import MiniProfileComponent from "./miniprofile.component.ts";
export default MiniProfileComponent;
</script>

// AussieTowns/ClientApp/app/components/shared/miniprofile.component.ts
﻿import { Component, Input, Output, EventEmitter } from '@angular/core';
import { User } from '../../model/user';

@Component({
    selector: 'miniprofile',
    template: require('./miniprofile.component.html'),
    styles: [require('./miniprofile.component.css')]
})
export class MiniProfileComponent {
    @Input() data: any;
    @Output() removeUser = new EventEmitter();

    userId: number;
    profileUrl: string;
    profileImageUrl: string;
    fullName: string;
    shortDescription: string;

    ngOnInit(): void {
        this.userId = this.data.id;
        this.profileImageUrl = this.data.photoUrl;
        this.fullName = this.data.fullname;
        this.shortDescription = this.data.shortDescription;
    }

    onRemoveUser() {
        this.removeUser.emit(this.data);
    }
}

﻿<div [id]="userId" class="miniprofile-wrapper">
    <div class="overlay" (click)="onRemoveUser()">
        <span class="glyphicon glyphicon-remove-sign"></span>
    </div>
    <div class="photo_wrapper">
        <a [href]="profileUrl" target="_blank">
            <img class="profile_photo_img" [src]="profileImageUrl" width="50" height="50" [alt]="fullName">
        </a>
    </div>
    <div class="text_wrapper">
        <div>
            <a class="user" [href]="profileUrl" target="_blank">{{fullName}}</a>
        </div>
        <div>
            <span>{{shortDescription}}</span>
        </div>
    </div>
</div>
