// AussieTown.VueClient/src/components/navmenu/navmenu.component.vue
﻿<template>
    <div id="header">
        <div class='nav-bar' v-bind:class="{ 'is-sticky': isSticky }">
            <router-link to="home" :class="{ 'hidden': hideNavToggle }">
				<div class='nav-bar__logo glyphicon glyphicon-home'></div>
			</router-link>

            <a @click="onNavToggle()" :class="{ 'hidden': !hideNavToggle }">
                <div class='nav-bar__logo glyphicon glyphicon-home'></div>
                <div class="nav-bar__toggle">
                    <i class="glyphicon glyphicon-chevron-down"></i>
                </div>
            </a>

            <div class='nav-bar__menu' :class="{'is-open': isMenuOpen, 'is-close': !isMenuOpen}">
                <ul>
                    <li active-class="link-active" class="nav-bar__menu-item">
                        <router-link class="nav-bar__menu-item-link" :to="{ name: 'tourdetail', params: { id: 6}}">
                            <span class='glyphicon glyphicon-th-list'></span> Tour Detail
                        </router-link>
                    </li>
                    <li v-if="!isLoggedin" class="nav-bar__menu-item" active-class="link-active">
                        <a class="nav-bar__menu-item-link" @click="loginModal.show()">
                            <span class='glyphicon glyphicon-th-list'></span> Log in
                        </a>
                    </li>
                    <li v-if="!isLoggedin" class="nav-bar__menu-item" active-class="link-active">
                        <a class="nav-bar__menu-item-link" @click="registerModal.show()">
                            <span class='glyphicon glyphicon-th-list'></span> Sign up
                        </a>
                    </li>

                    <li v-if="isLoggedin" class="nav-bar__menu-item">
                        <router-link class="nav-bar__menu-item-link" :to="{ name: 'profile', params: { id: 1}}"  active-class="link-active">
                            <span class='glyphicon glyphicon-th-list'></span> Hi
                        </router-link>
                    </li>

                    <li v-if="isLoggedin" class="nav-bar__menu-item">
                        <router-link class="nav-bar__menu-item-link" to="logout" @click="onLogout()">
                            <span class='glyphicon glyphicon-th-list'></span> Log out
                        </router-link>
                    </li>
                </ul>
            </div>

        </div>
    </div>
</template>

<script lang="ts">
    import NavMenuComponent from "./navmenu.component.ts";
    export default NavMenuComponent;
</script>

// AussieTowns/ClientApp/app/components/navmenu/navmenu.component.ts
import { Component, ViewChild } from '@angular/core';
import { RegistrationFormComponent } from '../forms/registrationform.component';
import { LoginFormComponent } from '../forms/loginform.component';

import { Cookie } from 'ng2-cookies';

import { isBrowser } from 'angular2-universal';

import { UserService } from '../../services/user.service';

declare var document: any;

@Component({
    selector: 'nav-menu',
    template: require('./navmenu.component.html'),
    styles: [require('./navmenu.component.css')]
})
export class NavMenuComponent {
    @ViewChild(RegistrationFormComponent) registerModal: RegistrationFormComponent;
    @ViewChild(LoginFormComponent) loginModal: LoginFormComponent;

    isLoggedin: boolean = false;
    name: string;

    constructor(private userService: UserService) {
        // Bodom: hack from here: https://github.com/aspnet/JavaScriptServices/issues/435
        if (isBrowser) {
            this.userService.getUserInfo().subscribe(
                data => {
                    this.isLoggedin = true;
                    this.name = data.Data.username;
                });
        }

    }

    handleLoggedIn(userName: string) {
        if (userName) {
            this.isLoggedin = true;
            this.name = userName;
        } else {
            this.isLoggedin = false;
        }
    }

    onLogout() {
        Cookie.delete("token");
        this.isLoggedin = false;
    }

    onTest() {
        this.userService.getUserInfo().subscribe(
            data => {
                var abc = data;
            });
    }
}

<div class='nav-bar' [ngClass]="{ 'is-sticky': isSticky }">
    <a [routerLink]="['/home']" title="Meet the Local" [hidden]="!hideNavToggle">
        <div class='nav-bar__logo glyphicon glyphicon-home'></div>
    </a>

    <a href="#" (click)="onNavToggle()" title="Meet the Local" [hidden]="hideNavToggle">
        <div class='nav-bar__logo glyphicon glyphicon-home'></div>
        <div class="nav-bar__toggle">
            <i class="glyphicon glyphicon-chevron-down"></i>
        </div>
    </a>

    <div class='nav-bar__menu' [ngClass]="{'is-open': isMenuOpen, 'is-close': !isMenuOpen}">
        <ul>
            <!--<li [routerLinkActive]="['link-active']">
                <a [routerLink]="['/counter']">
                    <span class='glyphicon glyphicon-education'></span> Counter
                </a>
            </li>
            <li [routerLinkActive]="['link-active']">
                <a [routerLink]="['/fetch-data']">
                    <span class='glyphicon glyphicon-th-list'></span> Fetch data
                </a>
            </li>
            <li [routerLinkActive]="['link-active']">
                <a [routerLink]="['/map']">
                    <span class='glyphicon glyphicon-th-list'></span> Map
                </a>
            </li>
            <li [routerLinkActive]="['link-active']">
                <a [routerLink]="['/tourdetail', 6]">
                    <span class='glyphicon glyphicon-th-list'></span> Tour Detail
                </a>
            </li>

            <li [routerLinkActive]="['link-active']">
                <a [routerLink]="['/tourrequest', 1]">
                    <span class='glyphicon glyphicon-th-list'></span> Tour Request
                </a>
            </li>
            <li [routerLinkActive]="['link-active']">
                <a [routerLink]="['/test']" (click)="onTest()">
                    <span class='glyphicon glyphicon-th-list'></span> Test
                </a>
            </li>-->
            <li [routerLinkActive]="['link-active']">
                <a [routerLink]="['/tourdetail', 6]">
                    <span class='glyphicon glyphicon-th-list'></span> Tour Detail
                </a>
            </li>
            <li *ngIf="!isLoggedin" class="nav-bar__menu-item" [routerLinkActive]="['link-active']">
                <a class="nav-bar__menu-item-link" [routerLink]="['/login']" (click)="loginModal.show()">
                    <span class='glyphicon glyphicon-th-list'></span> Log in
                </a>
            </li>
            <li *ngIf="!isLoggedin" class="nav-bar__menu-item" [routerLinkActive]="['link-active']">
                <a class="nav-bar__menu-item-link" [routerLink]="['/register']" (click)="registerModal.show()">
                    <span class='glyphicon glyphicon-th-list'></span> Sign up
                </a>
            </li>

            <li *ngIf="isLoggedin" class="nav-bar__menu-item" [routerLinkActive]="['link-active']">
                <a class="nav-bar__menu-item-link" [routerLink]="['/profile',id]">
                    <span class='glyphicon glyphicon-th-list'></span> Hi {{name}}
                </a>
            </li>

            <li *ngIf="isLoggedin" class="nav-bar__menu-item" [routerLinkActive]="['link-active']">
                <a class="nav-bar__menu-item-link" [routerLink]="['/logout']" (click)="onLogout()">
                    <span class='glyphicon glyphicon-th-list'></span> Log out
                </a>
            </li>
        </ul>
        <!--<a href="#" class="nav-bar__toggle" title="Navigation Menu" aria-hidden="true">
            <i class="fa fa-bars"></i>
        </a>-->
    </div>

</div>
<registrationform></registrationform>
<loginform (isLoggedIn)="handleLoggedIn($event)"></loginform>
