// AussieTown.VueClient/src/components/navmenu/navmenu.component.ts
import Vue from "vue";
import { Component, Inject, Watch, Prop } from "vue-property-decorator";
import LoginModal from '../modal/loginmodal.component.vue';
import RegistrationModal from '../modal/registrationmodal.component.vue';

@Component({
    name: 'nav-menu',
    components: {
        'loginmodal': LoginModal,
        'registrationmodal': RegistrationModal
    }
})
export default class NavMenuComponent extends Vue {
    logginInUserId: number = 0;
    name: string = "test";
    id: number;
    hideNavToggle = false;
    isMenuOpen = false;
    isSticky = false;

    showLoginModal: boolean = false;
    showRegistrationModal: boolean = false;

    onSuccessfulLogin(userId: number) {
        if (userId > 0) {
            this.logginInUserId = userId;
            this.showLoginModal = false;
        }
    }
    //ngOnInit() {
    //    if (isBrowser) {
    //        Observable.fromEvent(window, 'resize')
    //            .debounceTime(100)
    //            .subscribe(e => {
    //                this.onWindowResize();
    //            });

    //        Observable.fromEvent(window, 'scroll')
    //            .throttleTime(1000)
    //            .subscribe(e => {
    //                this.onWindowScroll();
    //            });
            

    //        this.onWindowResize();
    //    }
    //}

    //onWindowResize() {
    //    let windowMode = this.detectionService.getCurrentMode();
    //    if (windowMode == DeviceMode.Mobile) {
    //        this.hideNavToggle = false;
    //    } else {
    //        this.hideNavToggle = true;
    //    }
    //}

    //onWindowScroll() {
    //    this.isSticky = this.detectionService.isScrollOverHalfPage();
    //}

    //handleLoggedIn(loggedInfo) {
    //    if (loggedInfo) {
    //        this.isLoggedin = true;
    //        this.name = loggedInfo.name;
    //        this.id = loggedInfo.id;
    //    } else {
    //        this.isLoggedin = false;
    //    }
    //}

    //onLogout() {
    //    Cookie.delete("token");
    //    this.isLoggedin = false;
    //}

    //onTest() {
    //    this.userService.getUserInfo(1).subscribe(
    //        data => {
    //            var abc = data;
    //        });
    //}

    //onNavToggle() {
    //    this.isMenuOpen = !this.isMenuOpen;
    //    return false;
    //}
}

// AussieTowns/ClientApp/app/components/navmenu/navmenu.component.ts
import { Component, ViewChild } from '@angular/core';
import { Observable } from 'rxjs/Observable';

import { Cookie } from 'ng2-cookies';

import { isBrowser } from 'angular2-universal';

import { UserService } from '../../services/user.service';
import { DeviceDetectionService, DeviceMode } from '../shared/devicedetection.service';

import 'rxjs/add/operator/debounceTime';
import 'rxjs/add/operator/throttleTime';
import { RegistrationModalComponent } from '../modal/registrationmodal.component';
import { LoginModalComponent } from '../modal/loginmodal.component';

declare var document: any;

@Component({
    selector: 'nav-menu',
    template: require('./navmenu.component.html'),
    styles: [require('./navmenu.component.scss').toString()]
})
export class NavMenuComponent {
    @ViewChild(RegistrationModalComponent) registerModal: RegistrationModalComponent;
    @ViewChild(LoginModalComponent) loginModal: LoginModalComponent;

    isLoggedin: boolean = false;
    name: string;
    id: number;
    hideNavToggle = true;
    isMenuOpen = false;
    isSticky = false;

    constructor(private userService: UserService, private detectionService: DeviceDetectionService) {
        // Bodom: hack from here: https://github.com/aspnet/JavaScriptServices/issues/435
        if (isBrowser) {
            //this.userService.getUserInfo().subscribe(
            //    data => {
            //        this.isLoggedin = true;
            //        this.name = data.Data.FirstName;
            //    });

        }

    }

    ngOnInit() {
        if (isBrowser) {
            Observable.fromEvent(window, 'resize')
                .debounceTime(100)
                .subscribe(e => {
                    this.onWindowResize();
                });

            Observable.fromEvent(window, 'scroll')
                .throttleTime(1000)
                .subscribe(e => {
                    this.onWindowScroll();
                });
            

            this.onWindowResize();
        }
    }

    onWindowResize() {
        let windowMode = this.detectionService.getCurrentMode();
        if (windowMode == DeviceMode.Mobile) {
            this.hideNavToggle = false;
        } else {
            this.hideNavToggle = true;
        }
    }

    onWindowScroll() {
        this.isSticky = this.detectionService.isScrollOverHalfPage();
    }

    handleLoggedIn(loggedInfo) {
        if (loggedInfo) {
            this.isLoggedin = true;
            this.name = loggedInfo.name;
            this.id = loggedInfo.id;
        } else {
            this.isLoggedin = false;
        }
    }

    onLogout() {
        Cookie.delete("token");
        this.isLoggedin = false;
    }

    onTest() {
        this.userService.getUserInfo(1).subscribe(
            data => {
                var abc = data;
            });
    }

    onNavToggle() {
        this.isMenuOpen = !this.isMenuOpen;
        return false;
    }
}

<div class='nav-bar' [ngClass]="{ 'is-sticky': isSticky }">
    <a [routerLink]="['/home']" title="Meet the Local" [hidden]="!hideNavToggle">
        <div class='nav-bar__logo glyphicon glyphicon-home'></div>
    </a>

    <a href="#" (click)="onNavToggle()" title="Meet the Local" [hidden]="hideNavToggle">
        <div class='nav-bar__logo glyphicon glyphicon-home'></div>
        <div class="nav-bar__toggle">
            <i class="glyphicon glyphicon-chevron-down"></i>
        </div>
    </a>

    <div class='nav-bar__menu' [ngClass]="{'is-open': isMenuOpen, 'is-close': !isMenuOpen}">
        <ul>
            <!--<li [routerLinkActive]="['link-active']">
                <a [routerLink]="['/counter']">
                    <span class='glyphicon glyphicon-education'></span> Counter
                </a>
            </li>
            <li [routerLinkActive]="['link-active']">
                <a [routerLink]="['/fetch-data']">
                    <span class='glyphicon glyphicon-th-list'></span> Fetch data
                </a>
            </li>
            <li [routerLinkActive]="['link-active']">
                <a [routerLink]="['/map']">
                    <span class='glyphicon glyphicon-th-list'></span> Map
                </a>
            </li>
            <li [routerLinkActive]="['link-active']">
                <a [routerLink]="['/tourdetail', 6]">
                    <span class='glyphicon glyphicon-th-list'></span> Tour Detail
                </a>
            </li>

            <li [routerLinkActive]="['link-active']">
                <a [routerLink]="['/tourrequest', 1]">
                    <span class='glyphicon glyphicon-th-list'></span> Tour Request
                </a>
            </li>
            <li [routerLinkActive]="['link-active']">
                <a [routerLink]="['/test']" (click)="onTest()">
                    <span class='glyphicon glyphicon-th-list'></span> Test
                </a>
            </li>-->
            <li [routerLinkActive]="['link-active']">
                <a [routerLink]="['/tourdetail', 6]">
                    <span class='glyphicon glyphicon-th-list'></span> Tour Detail
                </a>
            </li>
            <li *ngIf="!isLoggedin" class="nav-bar__menu-item" [routerLinkActive]="['link-active']">
                <a class="nav-bar__menu-item-link" [routerLink]="['/login']" (click)="loginModal.show()">
                    <span class='glyphicon glyphicon-th-list'></span> Log in
                </a>
            </li>
            <li *ngIf="!isLoggedin" class="nav-bar__menu-item" [routerLinkActive]="['link-active']">
                <a class="nav-bar__menu-item-link" [routerLink]="['/register']" (click)="registerModal.show()">
                    <span class='glyphicon glyphicon-th-list'></span> Sign up
                </a>
            </li>

            <li *ngIf="isLoggedin" class="nav-bar__menu-item" [routerLinkActive]="['link-active']">
                <a class="nav-bar__menu-item-link" [routerLink]="['/profile',id]">
                    <span class='glyphicon glyphicon-th-list'></span> Hi {{name}}
                </a>
            </li>

            <li *ngIf="isLoggedin" class="nav-bar__menu-item" [routerLinkActive]="['link-active']">
                <a class="nav-bar__menu-item-link" [routerLink]="['/logout']" (click)="onLogout()">
                    <span class='glyphicon glyphicon-th-list'></span> Log out
                </a>
            </li>
        </ul>
        <!--<a href="#" class="nav-bar__toggle" title="Navigation Menu" aria-hidden="true">
            <i class="fa fa-bars"></i>
        </a>-->
    </div>

</div>
<registrationform></registrationform>
<loginform (isLoggedIn)="handleLoggedIn($event)"></loginform>
